-- The five basemap tables of the CI fixture, as load_basemap.py (through geopandas) creates them.
-- Generated by packages/atlas-data/tools/fixtures/basemap_fixture.py build. Do not edit by hand.
CREATE SCHEMA IF NOT EXISTS basemap;

CREATE TABLE basemap.landuse_region (
    code integer,
    fclass text,
    name text,
    osm_id text,
    geometry public.geometry(Geometry,4326)
);
CREATE TABLE basemap.places_region (
    code integer,
    fclass text,
    name text,
    osm_id text,
    population bigint,
    geometry public.geometry(Point,4326)
);
CREATE TABLE basemap.railways_vn (
    code integer,
    fclass text,
    name text,
    osm_id text,
    geometry public.geometry(LineString,4326)
);
CREATE TABLE basemap.roads_region (
    bridge text,
    code integer,
    fclass text,
    maxspeed integer,
    name text,
    oneway text,
    osm_id text,
    ref text,
    tunnel text,
    geometry public.geometry(LineString,4326)
);
CREATE TABLE basemap.water_region (
    code integer,
    fclass text,
    name text,
    osm_id text,
    geometry public.geometry(Geometry,4326)
);
CREATE INDEX idx_landuse_region_geometry ON basemap.landuse_region USING gist (geometry);
CREATE INDEX idx_places_region_geometry ON basemap.places_region USING gist (geometry);
CREATE INDEX idx_railways_vn_geometry ON basemap.railways_vn USING gist (geometry);
CREATE INDEX idx_roads_region_geometry ON basemap.roads_region USING gist (geometry);
CREATE INDEX idx_water_region_geometry ON basemap.water_region USING gist (geometry);
CREATE INDEX landuse_region_fclass_idx ON basemap.landuse_region USING btree (fclass);
CREATE INDEX places_region_fclass_idx ON basemap.places_region USING btree (fclass);
CREATE INDEX railways_vn_fclass_idx ON basemap.railways_vn USING btree (fclass);
CREATE INDEX roads_region_fclass_idx ON basemap.roads_region USING btree (fclass);
CREATE INDEX water_region_fclass_idx ON basemap.water_region USING btree (fclass);
